VentilationTrack/Controllers/VentilationTrackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VentilationTrack.Models;

namespace VentilationTrack.Controllers
{
    public class VentilationTrackController : Controller
    {
        private readonly VentilationContext _context;
        public VentilationTrackController(VentilationContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            VentilationMonitorModel model = new VentilationMonitorModel();

            model.LstDepartments = _context.Department.Where(p => p.IsActive).ToList();
            var lstEquipment = _context.Equipment.Where(p => p.IsActive).ToList();

            var lstEquipmentVentilationDetails = _context.EquipmentVentilationDetails.Where(p => p.Equipment.IsActive).ToList();

            model.LstVentilationMonitor = new List<VentilationMonitor>();

            if (lstEquipment != null)
            {
                foreach (var equipment in lstEquipment)
                {
                    VentilationMonitor ventilationMonitor = new VentilationMonitor();
                    ventilationMonitor.EquipmentId = equipment.ID;
                    ventilationMonitor.EquipmentName = equipment.Name;

                    ventilationMonitor.LstEquipmentVentilationDetails = new List<EquipmentVentilationDetails>();

                    if (model.LstDepartments != null)
                    {
                        foreach (var department in model.LstDepartments)
                        {
                            EquipmentVentilationDetails equipmentVentilationDetails = new EquipmentVentilationDetails();

                            equipmentVentilationDetails.DepartmentId = department.ID;

                            var ventilationDetails = lstEquipmentVentilationDetails.FirstOrDefault(p => p.DepartmentId == department.ID && p.EquipmentId == equipment.ID);
                            if (ventilationDetails != null)
                            {
                                equipmentVentilationDetails.ID = ventilationDetails.ID;
                                equipmentVentilationDetails.Capacity = ventilationDetails.Capacity;
                            }
                            ventilationMonitor.TotalCapacity = lstEquipmentVentilationDetails.Where(p => p.DepartmentId == department.ID).Sum(p => p.Capacity).ToString();

                            ventilationMonitor.LstEquipmentVentilationDetails.Add(equipmentVentilationDetails);
                        }
                    }

                    model.LstVentilationMonitor.Add(ventilationMonitor);

                }
            }

            return View(model);
        }

        public IActionResult AddNewEqupimentRow()
        {
            VentilationMonitorModel model = new VentilationMonitorModel();

            model.LstDepartments = _context.Department.Where(p => p.IsActive).ToList();

            //Create new equipment with Name 'New Equipment'
            var equipment = new Equipment()
            {
                Name = "New Equipment",
                IsActive = true
            };
            _context.Add(equipment);
            _context.SaveChanges();

            model.LstVentilationMonitor = new List<VentilationMonitor>();

            VentilationMonitor ventilationMonitor = new VentilationMonitor();
            ventilationMonitor.EquipmentId = equipment.ID;//equipment id;
            ventilationMonitor.EquipmentName = equipment.Name;// equipment.Name;

            ventilationMonitor.LstEquipmentVentilationDetails = new List<EquipmentVentilationDetails>();

            if (model.LstDepartments != null)
            {
                foreach (var department in model.LstDepartments)
                {
                    EquipmentVentilationDetails equipmentVentilationDetails = new EquipmentVentilationDetails();
                    equipmentVentilationDetails.DepartmentId = department.ID;

                    ventilationMonitor.LstEquipmentVentilationDetails.Add(equipmentVentilationDetails);
                }
            }

            return PartialView("~/Views/VentilationTrack/_VentilationEquipmentRow.cshtml", ventilationMonitor);
        }

        [HttpPost]
        public IActionResult DeleteEqupimentRow(int equipmentId)
        {
            var equipment = _context.Equipment.FirstOrDefault(o => o.ID == equipmentId);
            equipment.IsActive = false;

            _context.Entry(equipment).State = EntityState.Modified;
            _context.SaveChanges();

            return Json(true);
        }

        [HttpPost]
        public IActionResult SaveUpdateEquipment(int equipmentId, string equipmentName)
        {
            var equipment = _context.Equipment.FirstOrDefault(o => o.ID == equipmentId);
            equipment.Name = equipmentName;

            _context.Entry(equipment).State = EntityState.Modified;
            _context.SaveChanges();

            return Json(true);
        }

        [HttpPost]
        public IActionResult SaveUpdateEquipmentCapacity(int equipmentId, int departmentId, int ventilationId, int capacity)
        {
            EquipmentVentilationDetails equipmentVentilationDetails = new EquipmentVentilationDetails()
            {
                DepartmentId = departmentId,
                EquipmentId = equipmentId,
                Capacity = capacity
            };

            if (ventilationId == 0)
            {
                _context.Add(equipmentVentilationDetails);
            }
            else
            {
                equipmentVentilationDetails = _context.EquipmentVentilationDetails.FirstOrDefault(o => o.ID == ventilationId);
                equipmentVentilationDetails.Capacity = capacity;
                _context.Entry(equipmentVentilationDetails).State = EntityState.Modified;
            }

            _context.SaveChanges();

            return Json(new { status = true, ventilationId = equipmentVentilationDetails.ID });
        }


    }
}

VentilationTrack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ventilation Monitor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/datatable/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 custom-navigation">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="VentilationTrack" asp-action="Index">Ventilation Monitor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2020 - VentilationTrack - <a asp-area="" asp-controller="VentilationTrack" asp-action="Privacy">Privacy</a>
        </div>
    </footer> 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/datatable/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>